{% set version = "1.1.6" %}

package:
  name: slirp4netns
  version: {{ version }}

source:
  url: https://github.com/rootless-containers/slirp4netns/archive/v{{ version }}.tar.gz
  sha256: 5047a46677bbfcd5d4ea865b2a1d2145a8e4ba429c6f2770df15d86559e759b8
  patches:
    - 0001-Add-missing-defines-for-CentOS-6.patch
    - 0002-Do-not-use-SCMP_ACT_KILL_PROCESS.patch

build:
  number: 0
  skip: true  # [not linux]
  ignore_run_exports:
    # slirp4netns uses defines from libcap but does not link to it.
    - libcap

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf >=2.69
    - automake >=1.9
    - make
    - pkg-config >=0.9.0
  host:
    # NOTE: The conda-forge-pinning is at version 2.58 (as of 2020-11-04).
    #       Only `>2.66.1` (and a few older builds) has the the libglib split.
    #       TODO: Remove version constraint once pinning is updated.
    - glib >=2.0
    # Header+pkgconfig files for libglib are in the glib package.
    # Explicitly depend on libglib to avoid glib run_exports from older builds.
    - libglib >=2.0
    - libslirp >=4.1.0
    - libcap
    - libseccomp
  run:

test:
  commands:
    - slirp4netns --help
    - slirp4netns --version

about:
  home: https://github.com/rootless-containers/slirp4netns
  dev_url: https://github.com/rootless-containers/slirp4netns
  doc_url: https://github.com/rootless-containers/slirp4netns
  license: GPL-2.0-or-later AND MIT
  license_file:
    - COPYING
    - vendor/parson/LICENSE
  summary: User-mode networking for unprivileged network namespaces.
  description: >
    slirp4netns provides user-mode networking ("slirp") for unprivileged network namespaces.

extra:
  recipe-maintainers:
    - mbargull
