{% set version = "1.1.11" %}

package:
  name: slirp4netns
  version: {{ version }}

source:
  url: https://github.com/rootless-containers/slirp4netns/archive/v{{ version }}.tar.gz
  sha256: 87a8909746781d995b1b49eb36540e6ee745599f983c18f9b4e927ec92d86eb6
  patches:
    - 0001-Add-missing-defines-for-CentOS-6.patch

build:
  number: 0
  skip: true  # [not linux]
  ignore_run_exports:
    # slirp4netns uses defines from libcap but does not link to it.
    - libcap

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf >=2.69
    - automake >=1.11.2
    - make
    - pkg-config >=0.9.0
  host:
    - glib
    # Header+pkgconfig files for libglib are in the glib package.
    - libglib
    - libslirp >=4.1.0
    - libslirp
    - libcap
    - libseccomp
  run:

test:
  commands:
    - slirp4netns --help
    - slirp4netns --version

about:
  home: https://github.com/rootless-containers/slirp4netns
  dev_url: https://github.com/rootless-containers/slirp4netns
  doc_url: https://github.com/rootless-containers/slirp4netns
  license: GPL-2.0-or-later AND MIT
  license_file:
    - COPYING
    - vendor/parson/LICENSE
  summary: User-mode networking for unprivileged network namespaces.
  description: >
    slirp4netns provides user-mode networking ("slirp") for unprivileged network namespaces.

extra:
  recipe-maintainers:
    - mbargull
